version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0 # broker id编号
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # zk地址
      KAFKA_ADVERTISED_HOST_NAME: 192.168.43.173 # 修改:宿主机IP ifconfig en0
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.43.173:9092 # 修改:宿主机IP ifconfig en0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper
  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1 # broker id编号
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # zk地址
      KAFKA_ADVERTISED_HOST_NAME: 192.168.43.173 # 修改:宿主机IP ifconfig en0
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.43.173:9093 # 修改:宿主机IP ifconfig en0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
    depends_on:
      - zookeeper
  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 2 # broker id编号
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181 # zk地址
      KAFKA_ADVERTISED_HOST_NAME: 192.168.43.173 # 修改:宿主机IP ifconfig en0
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.43.173:9094 # 修改:宿主机IP ifconfig en0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
    depends_on:
      - zookeeper
  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
