version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: rootadmin
    networks:
      - prom
  mysql_export:
    depends_on:
      - mysql
    image: prom/mysqld-exporter
    container_name: mysql_exporter
    ports:
      - 9104:9104
    environment:
      DATA_SOURCE_NAME: root:rootadmin@(mysql:3306)/
    networks:
      - prom
  node_export:
    image: quay.io/prometheus/node-exporter
    container_name: node_export
    ports:
      - 9100:9100
    networks:
      - prom
  promeserver:
    image: promeserver
    container_name: server_monitor
    ports:
      - 4433:4433
    networks:
      - prom
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - type: bind
        source: ./alertmanager/alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
      - type: bind
        source: ./alertmanager/tmpl
        target: /etc/alertmanager-tmpl
    ports:
      - 9093:9093
    networks:
      - prom
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - type: bind
        source: ./prometheus/rules
        target: /etc/prometheus/rules
    ports:
      - 9090:9090
    networks:
      - prom
  grafana:
    depends_on:
      - prometheus
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - prom

networks:
  prom:
    driver: bridge