global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "/etc/prometheus/rules/*.rules"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node_export'
    static_configs:
      - targets: ['node_export:9100']
  - job_name: 'mysql_export'
    static_configs:
      - targets: ['mysql_export:9104']
  - job_name: 'server_monitor'
    static_configs:
      - targets: ['server_monitor:4433']